Configuration:
  DisablePathCorrection: false
  EnablePathEscape: false
  FireMethodNotAllowed: false
  DisableBodyConsumptionOnUnmarshal: true
  TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
  Charset: UTF-8

#自定义配置
own:
  separate: false
  port: 8888
  ignore_urls: [/api/admin/user/login, /echo]
  jwt_timeout: 120 #minute
  log_level: debug
  secret: xxx-Secret
  websocket_pool: 100
  domain: a

postgresql:
  host: 127.0.0.1
  port: 5432
  dbname: postgres
  username: postgres
  password: daiqijin